<?xml version="1.0" encoding="utf-8"?><Database Name="grobot" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=97.113.20.51,50612;Initial Catalog=grobot;Persist Security Info=True;User ID=TestLog" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="grobotConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GardenBeds" Member="GardenBeds">
    <Type Name="GardenBed">
      <Column Name="bedID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bedName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="length" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GardenBed_BedFeedbackValue" Member="BedFeedbackValue" ThisKey="bedID" OtherKey="bedID" Type="BedFeedbackValue" Cardinality="One" />
      <Association Name="PlantType_GardenBed" Member="PlantType" ThisKey="typeID" OtherKey="typeID" Type="PlantType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlantTypes" Member="PlantTypes">
    <Type Name="PlantType">
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="typeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cycle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recWaterPerDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recFertilizerPerMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lowestTemp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="highestTemp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lowestMoisture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="highestMoisture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PlantType_GardenBed" Member="GardenBeds" ThisKey="typeID" OtherKey="typeID" Type="GardenBed" />
    </Type>
  </Table>
  <Table Name="dbo.BedFeedbackValues" Member="BedFeedbackValues">
    <Type Name="BedFeedbackValue">
      <Column Name="bedID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="temperature" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="moisture" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="light" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="currentDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GardenBed_BedFeedbackValue" Member="GardenBed" ThisKey="bedID" OtherKey="bedID" Type="GardenBed" IsForeignKey="true" />
    </Type>
  </Table>
</Database>